SET IDENTITY_INSERT [dbo].[BrandNameTbl] ON
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (1, N'Samsung')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (2, N'Apple')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (3, N'Apple')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (4, N'Boat')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (5, N'Sonic')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (6, N'OnePlus')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (7, N'OnePlus')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (8, N'OnePlus')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (9, N'OnePlus')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (10, N'')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (11, N'')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (12, N'')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (13, N'')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (14, N'Truke')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (15, N'Truke')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (16, N'Truke')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (17, N'Xr+')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (18, N'GT168')
INSERT INTO [dbo].[BrandNameTbl] ([Id], [BrandName]) VALUES (19, N'XR200')
SET IDENTITY_INSERT [dbo].[BrandNameTbl] OFF
TRUNCATE Table BrandNameTbl;